config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'

  root 'movies#index'

  resources :admin_users do
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  resources :comments do
    member do
      get :delete
    end
  end

  resources :followers do
    member do
      get :followerlist
      get :followeelist
      post :follow
      delete :unfollow
    end
  end

  resources :movies do
    member do
      get :delete
    end
    resources :reviews, only: %i[new create index show]
  end

  resource :password_reset, only: %i[new create edit update]

  resources :reviews do
    member do
      get :delete
    end
    resources :comments, only: %i[destroy create]
  end

  resources :users do
    member do
      get :delete
    end
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies=Movie.sorted_by_title
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.includes(:user)
  
    @average_rating = @reviews.average(:rating).to_f || 0
  end
  



  def edit
    @movie=Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end 



  def new
    @movie=Movie.new
  end

  def create
    @movie=Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end



  def delete
    @movie=Movie.find(params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path, notice: 'Movie was successfully deleted.'
    else
      redirect_to movies_path, alert: 'Failed to delete movie.'
    end
  end


  private

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :synopsis)
  end

end

app/views/movies/delete.html.erb
<h2 class="text-center text-2xl font-bold mb-4">Confirm Delete Movie</h2>

<p class="text-center mb-8">Are you sure you want to delete <%= @movie.title %>?</p>

<div class="flex justify-center space-x-4">
  <%= link_to 'Cancel', movie_path(@movie), class: 'py-2 px-4 bg-gray-300 text-gray-800 font-semibold rounded-lg shadow-md hover:bg-gray-400 focus:outline-none focus:ring focus:ring-gray-300' %>
  
  <%= button_to  'Delete', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' }, class: 'py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300' %>
</div>

app/views/movies/edit.html.erb
<h2 class="text-2xl font-bold mb-6 text-center">Edit Movie</h2>
  <!-- Profile Picture Section -->
<div class="flex justify-center mb-6">
  <% if @movie.movie_cover.attached? %>
    <%= image_tag url_for(@movie.movie_cover), class: 'w-100 h-50 object-cover' %>
  <% else %>
    <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNO3hziJ9HVvBASDh6lMDRX3p6eS_Fb4dvWN0pGyaGETX6yYt3PAl9mBgrqQFPE1fGDTU&usqp=CAU', class: 'w-48 h-32 object-cover' %>
  <% end %>
</div>

<div class="flex justify-center">
  <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
    <%= form_with model: @movie, url: movie_path(@movie), method: :patch, local: true, class: "space-y-6" do |form| %>
          <!-- Profile Picture Upload Field -->
      <div class="mb-4">
        <%= form.label :movie_cover, class: 'block text-gray-700' %>
        <%= form.file_field :movie_cover, class: 'w-full p-2 border border-gray-300 rounded mt-1' %>
      </div>
      
      <div>
        <%= form.label :title, class: "block text-gray-700" %>
        <%= form.text_field :title, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
      </div>

      <div>
        <%= form.label :release_date, class: "block text-gray-700" %>
        <%= form.date_field :release_date, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
      </div>

      <div>
        <%= form.label :director, class: "block text-gray-700" %>
        <%= form.text_field :director, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
      </div>

      <div>
        <%= form.label :synopsis, class: "block text-gray-700" %>
        <%= form.text_area :synopsis, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="flex justify-between">
        <%= link_to 'Cancel', movie_path(@movie), class: 'py-2 px-4 bg-gray-300 text-gray-800 font-semibold rounded-lg shadow-md hover:bg-gray-400 focus:outline-none focus:ring focus:ring-gray-300' %>
        <%= form.submit "Update Movie", class: 'py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300' %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="flex justify-between items-center p-4">
  <h1 class="text-2xl font-bold mb-6"><%= t('movies.index.title') %></h1>
  <% if !logged_in? %>
    <div class="flex space-x-4">
      <%= link_to t('movies.index.login'), login_users_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <%= link_to t('movies.index.sign_up'), new_user_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
  <% @movies.each do |movie| %>
    <div class="card bg-white rounded-lg overflow-hidden shadow-md cursor-pointer">
      <!-- Movie Image -->
      <div class="w-full h-48 overflow-hidden">
        <% if movie.movie_cover.attached? %>
          <%= image_tag url_for(movie.movie_cover), class: 'w-full h-full object-cover' %>
        <% else %>
          <img src="https://via.placeholder.com/300" alt="<%= t('movies.index.movie_image_alt') %>" class="w-full h-full object-cover">
        <% end %>
      </div>
      <div class="p-4">
        <!-- Movie Title -->
        <h2 class="text-xl font-bold mb-2">
          <%= link_to movie.title, movie_path(movie), class: "text-blue-500 hover:text-blue-700" %>
        </h2>

        <!-- Movie Rating -->
        <div class="flex items-center mb-2">
          <svg class="h-5 w-5 text-yellow-500 fill-current mr-1" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M10 1L12.2451 6.47214L18.4902 7.11803L13.7451 11.0279L15.4902 17L10 13.7634L4.5098 17L6.2549 11.0279L1.5098 7.11803L7.7549 6.47214L10 1Z"/>
          </svg>
          <span class="text-gray-600"><%= t('movies.index.rating_placeholder') %></span> <!-- Replace with movie rating -->
        </div>

        <!-- Number of Reviews -->
        <div class="text-gray-600 mb-4">
          <span><%= pluralize(movie.reviews.count, t('movies.index.reviews.one'), t('movies.index.reviews.other')) %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1 class="text-2xl font-bold mb-6">Add New Movie</h1>

<div class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow-md">
  <%= form_with model: @movie, local: true, class: "space-y-6" do |form| %>
    <div>
      <%= form.label :title, class: "block text-gray-700" %>
      <%= form.text_field :title, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
    </div>

    <div>
      <%= form.label :release_date, class: "block text-gray-700" %>
      <%= form.date_field :release_date, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
    </div>

    <div>
      <%= form.label :director, class: "block text-gray-700" %>
      <%= form.text_field :director, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
    </div>

    <div>
      <%= form.label :synopsis, class: "block text-gray-700" %>
      <%= form.text_area :synopsis, rows: 5, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :movie_cover, class: 'block text-gray-700' %>
      <%= form.file_field :movie_cover, class: 'w-full p-2 border border-gray-300 rounded mt-1' %>
   </div>

    <div>
      <%= form.submit "Add Movie", class: "w-full py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>
  <% end %>

  <%= link_to 'Back to Movie List', movies_path, class: "mt-4 inline-block py-2 px-4 bg-gray-500 text-white font-semibold rounded-lg shadow-md hover:bg-gray-600 focus:outline-none focus:ring focus:ring-gray-300" %>
</div>

app/views/movies/show.html.erb
<div class="bg-white p-8 rounded-lg shadow-md max-w-4xl mx-auto">

  <div class="flex justify-center mb-6">
    <% if @movie.movie_cover.attached? %>
      <%= image_tag url_for(@movie.movie_cover), class: 'w-72 h-96 object-cover' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNO3hziJ9HVvBASDh6lMDRX3p6eS_Fb4dvWN0pGyaGETX6yYt3PAl9mBgrqQFPE1fGDTU&usqp=CAU', class: 'w-72 h-96 object-cover' %>
    <% end %>
  </div>

  <h1 class="text-3xl font-bold mb-6 text-center"><%= @movie.title %></h1>
  <p class="text-xl font-semibold mb-4"><strong><%= t('movies.show.director') %>:</strong> <%= @movie.director %></p>
  <p class="text-xl font-semibold mb-4"><strong><%= t('movies.show.rating') %>:</strong> <%= @average_rating %></p>
  <p class="text-xl mb-4"><strong><%= t('movies.show.synopsis') %>:</strong> <%= @movie.synopsis %></p>

  <!-- Display Genres as buttons -->
  <div class="flex flex-wrap gap-2 mb-4">
    <% @movie.genres.each do |genre| %>
      <button class="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-lg">
        <%= (genre.genre_type) %>
      </button> 
    <% end %>
  </div> 

  <br/>

  <% if current_admin != nil %>
    <div class="flex justify-between mt-6">
      <%= link_to t('movies.show.edit_movie'), edit_movie_path(@movie), class: 'py-2 px-4 bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300' %>
      <%= button_to  'Delete', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' }, class: 'py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300' %>    </div>
  <% end %>

  <br/>

  <div class="flex justify-between">
    <%= link_to t('movies.show.back_to_list'), movies_path, class: 'py-2 px-4 bg-gray-300 text-gray-800 font-semibold rounded-lg shadow-md hover:bg-gray-400 focus:outline-none focus:ring focus:ring-gray-300' %>
  </div>

  <br/><br/>

  <hr class="my-6">
  <h2 class="text-2xl font-bold mb-4 text-center"><%= t('movies.show.user_reviews') %></h2>
  <div class="bg-gray-100 p-4 rounded-lg">
    <% if @reviews.any? %>
      <table class="min-w-full bg-white">
        <thead class="bg-gray-800 text-white">
          <tr>
            <th class="py-2 px-4"><%= t('movies.show.user') %></th>
            <th class="py-2 px-4"><%= t('movies.show.review') %></th>
            <th class="py-2 px-4"><%= t('movies.show.rating') %></th>
            <th class="py-2 px-4"><%= t('movies.show.comments') %></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr class="bg-gray-100">
              <td class="border px-4 py-2">
                <% if review.user.profile_picture.attached? %>
                  <%= image_tag url_for(review.user.profile_picture), size: "50x50", class: 'rounded-full mr-2' %>
                <% else %>
                  <%= image_tag 'https://st.depositphotos.com/2218212/2938/i/450/depositphotos_29387653-stock-photo-facebook-profile.jpg', size: "50x50", class: 'rounded-full mr-2' %>
                <% end %>
                <%= link_to "#{review.user.first_name} #{review.user.last_name}", user_path(review.user), class: 'text-blue-500 hover:text-blue-700 font-semibold' %>
              </td>
              <td class="border px-4 py-2"><%= truncate(review.review, length: 100) %></td>
              <td class="border px-4 py-2"><%= review.rating %></td>
              <td class="border px-4 py-2">
                <%= link_to t('movies.show.comments'), review_path(review), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="text-center"><%= t('movies.show.no_reviews') %></p>
    <% end %>
  </div>

  <div class="bg-white p-4 rounded-lg shadow-md mt-6">
    <h2 class="text-xl font-bold mb-4"><%= t('movies.show.add_review') %></h2>
    <%= form_with model: [ @movie, Review.new ], local: true do |form| %>
      <div class="mb-4">
       <%= form.label :rating, class: "block text-gray-700" %>
        <div class="flex items-center space-x-1">
         <% (1..10).each do |i| %>
            <%= form.radio_button :rating, i, id: "rating_#{i}", class: 'hidden' %>
            <label for="rating_<%= i %>" class="star cursor-pointer text-gray-300 hover:text-yellow-400 text-3xl">&#9733;</label>
          <% end %>
        </div>
      </div>
      <div class="mb-4">
        <%= form.label :review, class: "block text-gray-700" %>
        <%= form.text_area :review, rows: 4, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:ring focus:ring-blue-300", required: true %>
      </div>
      <div>
        <%= form.submit t('movies.show.submit_review'), class: 'py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300' %>
      </div>
    <% end %>
  </div>



</div>