config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'

  root 'movies#index'

  resources :admin_users do
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  resources :comments do
    member do
      get :delete
    end
  end

  resources :followers do
    member do
      get :followerlist
      get :followeelist
      post :follow
      delete :unfollow
    end
  end

  resources :movies do
    member do
      get :delete
    end
    resources :reviews, only: %i[new create index show]
  end

  resource :password_reset, only: %i[new create edit update]

  resources :reviews do
    member do
      get :delete
    end
    resources :comments, only: %i[destroy create]
  end

  resources :users do
    member do
      get :delete
    end
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/reviews_controller.rb
# This is review controller
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index; end

  def show
    # @review = Review.find(params[:id])
    @movie = @review.movie
    @user = @review.user
  end

  def new; end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new(review_params)
    @review.user = current_user # or however you get the current user

    if @review.save
      redirect_to @movie, notice: 'Review was successfully created.'
    else
      @reviews = @movie.reviews.includes(:user)
      @average_rating = @reviews.average(:rating).to_f.round(2)
      render 'movies/show'
    end
  end

  def edit
    # the @review variable is already set using the set_review method
  end

  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def delete
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])

    if (current_user && @review.user_id == current_user.id) || current_admin
      @review.destroy
      redirect_to movie_path(@review.movie), notice: 'Review was successfully deleted.'
    else
      redirect_to movie_path(@review.movie), alert: 'You do not have permission to delete this review.'
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to movies_path, alert: 'Review not found.'
  end

  private

  def review_params
    params.require(:review).permit(:rating, :review)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="bg-white p-8 rounded-lg shadow-md max-w-4xl mx-auto">
  <h1 class="text-3xl font-bold mb-6 text-center"><%= t('reviews.edit.heading', movie_title: @review.movie.title) %></h1>

  <div class="bg-white p-4 rounded-lg shadow-md mt-6">
    <%= form_with model: @review, local: true do |form| %>
      <div class="mb-4">
        <%= form.label :rating, t('reviews.edit.rating_label'), class: "block text-gray-700" %>
        <div class="flex items-center space-x-1">
          <% (1..10).each do |i| %>
            <%= form.radio_button :rating, i, id: "rating_#{i}", value: i, class: 'hidden' %>
            <label for="rating_<%= i %>" class="star cursor-pointer text-gray-300 hover:text-yellow-400 text-3xl">&#9733;</label>
          <% end %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :review, t('reviews.edit.review_label'), class: "block text-gray-700" %>
        <%= form.text_area :review, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:ring focus:ring-blue-300", required: true %>
      </div>

      <div class="flex justify-end">
        <%= form.submit t('reviews.edit.update_review_button'), class: "py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-300" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="bg-white p-8 rounded-lg shadow-md max-w-4xl mx-auto">
  <div class="flex justify-center mb-6">
    <% if @movie.movie_cover.attached? %>
      <%= image_tag url_for(@movie.movie_cover), class: 'w-72 h-96 object-cover' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNO3hziJ9HVvBASDh6lMDRX3p6eS_Fb4dvWN0pGyaGETX6yYt3PAl9mBgrqQFPE1fGDTU&usqp=CAU', class: 'w-72 h-96 object-cover' %>
    <% end %>
  </div>
  <h1 class="text-3xl font-bold mb-6 text-center"><%= @review.movie.title %></h1>
  <div class="flex justify-left mb-6">
    <% if @user.profile_picture.attached? %>
      <%= image_tag url_for(@user.profile_picture), class: 'w-32 h-32 rounded-full object-cover' %>
    <% else %>
      <%= image_tag 'https://st.depositphotos.com/2218212/2938/i/450/depositphotos_29387653-stock-photo-facebook-profile.jpg', class: 'w-32 h-32 rounded-full object-cover' %>
    <% end %>
  </div>
  <p class="text-xl font-semibold mb-4"><strong><%= t('reviews.show.user') %>:</strong> <%= @review.user.first_name %> <%= @review.user.last_name %></p>
  <p class="text-xl font-semibold mb-4"><strong><%= t('reviews.show.rating') %>:</strong> <%= @review.rating %></p>
  <p class="text-xl mb-4"><strong><%= t('reviews.show.review') %>:</strong> <%= @review.review %></p>

  <% if current_user != nil and @review.user_id == current_user.id %>
    <div class="flex justify-between mb-4">
      <%= link_to t('reviews.show.edit_review'), edit_review_path(@review), class: 'py-2 px-4 bg-yellow-500 text-white font-semibold rounded-lg shadow-md hover:bg-yellow-600 focus:outline-none focus:ring focus:ring-yellow-300' %>
      <%= button_to t('reviews.show.delete_review'), review_path(@review), method: :delete, data: { confirm: t('reviews.show.confirm_delete_review') }, class: 'py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300' %>
    </div>
  <% end %>

  <% if current_admin != nil %>
    <div class="flex justify-between mt-6">
      <%= button_to t('reviews.show.delete_review'), review_path(@review), method: :delete, class: 'py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-600 focus:outline-none focus:ring focus:ring-red-300' %>
    </div>
    <br/>
  <% end %>

  <div class="flex justify-between">
    <%= link_to t('reviews.show.back_to_movie_review'), movie_path(@review.movie.id), class: 'py-2 px-4 bg-gray-300 text-gray-800 font-semibold rounded-lg shadow-md hover:bg-gray-400 focus:outline-none focus:ring focus:ring-gray-300' %>
  </div>

  <hr class="my-6">
  <h2 class="text-2xl font-bold mb-4 text-center"><%= t('reviews.show.comments') %></h2>
  <div class="bg-gray-100 p-4 rounded-lg">
    <% if @review.comments.any? %>
      <table class="min-w-full bg-white">
        <thead class="bg-gray-800 text-white">
          <tr>
            <th class="py-2 px-4"><%= t('reviews.show.user_name') %></th>
            <th class="py-2 px-4"><%= t('reviews.show.comment') %></th>
            <th class="py-2 px-4"><%= t('reviews.show.action') %></th>
          </tr>
        </thead>
        <tbody>
          <% @review.comments.each do |comment| %>
            <tr class="bg-gray-100">
              <td class="border px-4 py-2">
                <% if comment.user.profile_picture.attached? %>
                  <%= image_tag url_for(comment.user.profile_picture), size: "50x50", class: 'rounded-full mr-2' %>
                <% else %>
                  <%= image_tag 'https://st.depositphotos.com/2218212/2938/i/450/depositphotos_29387653-stock-photo-facebook-profile.jpg', size: "50x50",class: 'rounded-full mr-2' %>
                <% end %>
                <%= link_to "#{comment.user.first_name} #{comment.user.last_name}", user_path(comment.user), class: 'text-blue-500 hover:text-blue-700' %>
              </td>
              <td class="border px-4 py-2"><%= comment.comment %></td>
              <td class="border px-2 py-2">
              <div class="flex justify-center space-x-2">
                <% if current_user != nil and comment.user_id == current_user.id %>
                  <%= link_to t('reviews.show.edit'), edit_comment_path(comment), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-3 rounded' %>
                  <%= button_to t('reviews.show.delete'), comment_path(comment), method: :delete, data: { confirm: t('reviews.show.confirm_delete_comment') }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-3 rounded' %>
                <% end %>
            
                <% if current_admin != nil %>
                  <%= button_to t('reviews.show.delete'), comment_path(comment), method: :delete, data: { confirm: t('reviews.show.confirm_delete_comment') }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-3 rounded' %>
                <% end %>
              </div>
            </td>
            
            
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="text-center"><%= t('reviews.show.no_comments') %></p>
    <% end %>
  </div>

  <hr class="my-6">
  <h2 class="text-2xl font-bold mb-4 text-center"><%= t('reviews.show.add_comment') %></h2>
  <div class="bg-white p-4 rounded-lg shadow-md mt-6">
    <%= form_with model: [@review, Comment.new], local: true do |form| %>
      <div class="mb-4">
        <%= form.label :comment, t('reviews.show.comment_label'), class: "block text-gray-700" %>
        <%= form.text_area :comment, class: "mt-1 p-2 w-full border rounded-lg focus:outline-none focus:shadow-outline", required: true %>
      </div>
      <div class="flex justify-end">
        <%= form.submit t('reviews.show.submit'), class: "py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-300" %>
      </div>
    <% end %>
  </div>
</div>