config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'

  root 'movies#index'

  resources :admin_users do
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  resources :comments do
    member do
      get :delete
    end
  end

  resources :followers do
    member do
      get :followerlist
      get :followeelist
      post :follow
      delete :unfollow
    end
  end

  resources :movies do
    member do
      get :delete
    end
    resources :reviews, only: %i[new create index show]
  end

  resource :password_reset, only: %i[new create edit update]

  resources :reviews do
    member do
      get :delete
    end
    resources :comments, only: %i[destroy create]
  end

  resources :users do
    member do
      get :delete
    end
    collection do
      get :login
      post :attempt_login
      delete :logout
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/admin_dashboard.html.erb
<!-- app/views/layouts/admin_dashboard.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title><%= t('layouts.admin_dashboard.title') %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font" %>
  <%= stylesheet_link_tag "application" %>

  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-100">

  <% if flash.any? %>
    <% flash.each do |key, value| %>
      <div class="flash <%= flash_class(key) %> p-4 rounded mb-4">
          <%= value %>
      </div>
    <% end %>
  <% end %>

  <div class="min-h-screen flex">
    <div class="bg-gray-800 text-white w-64 p-6">
      <h1 class="text-2xl font-bold mb-6"><%= t('layouts.admin_dashboard.admin_panel') %></h1>
      <ul class="space-y-4">
        <li><%= link_to t('layouts.admin_dashboard.user_list'), users_path, class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= link_to t('layouts.admin_dashboard.movie_list'), movies_path, class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= link_to t('layouts.admin_dashboard.add_movie'), new_movie_path, class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= button_to t('layouts.admin_dashboard.log_out'), logout_admin_users_path, method: :delete, class: "block py-2 px-4 hover:bg-gray-700" %></li>
      </ul>
    </div>
    <div class="flex-1">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font" %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
      <% flash.each do |key, value| %>
        <div class="flash <%= flash_class(key) %> p-4 rounded mb-4">
          <%= value %>
        </div>
      <% end %>
   

    <%= yield %>
  </body>
</html>

app/views/layouts/user_dashboard.html.erb
<!-- app/views/layouts/user_dashboard.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title><%= t('layouts.user_dashboard.title') %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "tailwind", "inter-font" %>
  <%= stylesheet_link_tag "application" %>
  
  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-100">

  <% if flash.any? %>
    <% flash.each do |key, value| %>
      <div class="flash <%= flash_class(key) %> p-4 rounded mb-4">
          <%= value %>
      </div>
    <% end %>
  <% end %>

  <div class="min-h-screen flex">
    <% if current_user %>
      <div class="bg-gray-800 text-white w-64 p-6">
        <h1 class="text-2xl font-bold mb-6"><%= t('layouts.user_dashboard.user_panel') %></h1>
        <ul class="space-y-4">
          <li><%= link_to t('layouts.user_dashboard.user_profile'), user_path(current_user), class: "block py-2 px-4 hover:bg-gray-700" %></li>
          <li><%= link_to t('layouts.user_dashboard.movie_list'), movies_path, class: "block py-2 px-4 hover:bg-gray-700" %></li>
          <li><%= button_to t('layouts.user_dashboard.log_out'), logout_users_path, method: :delete, data: { turbo: false }, class: "block py-2 px-4 hover:bg-gray-700" %></li>
        </ul>
      </div>
    <% end %>
    <div class="flex-1">
      <%= yield %>
    </div>
  </div>
</body>
</html>